apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

namePrefix: prod-

commonLabels:
  environment: prod

bases:
  - ../base

patches:
  - path: patches/deployment-patch.yaml

resources:
  - hpa.yaml

images:
  - name: rom55555/classificateur-ia
    newTag: v1.0.0
