apiVersion: v1
kind: Service
metadata:
  name: classificateur-ia-service
spec:
  type: LoadBalancer
  selector:
    app: classificateur-ia
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501
