apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linstor-config
  namespace: argocd
spec:
  destination:
    namespace: piraeus-datastore
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/romainfaure-ascenzia/classificateur-ia.git
    targetRevision: main
    path: k8s/infrastructure/linstor
  syncPolicy:
    automated:
      prune: false      # CRITIQUE : Ne jamais supprimer automatiquement
      selfHeal: false   # Pas de heal automatique pour le storage
    syncOptions:
    - CreateNamespace=true
