apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

namePrefix: staging-

commonLabels:
  environment: staging

bases:
  - ../base

patches:
  - path: patches/deployment-patch.yaml

images:
  - name: rom55555/classificateur-ia
    newTag: v1.0.0
